name: changelogs

on:
  push:
    branches:
      - '**'

jobs:
  update_changelogs:
    runs-on: ubuntu-20.04
    outputs:
      output1: ${{ steps.gitversion.outputs.version }}
      output2: ${{ steps.latesttag.outputs.tag }}
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install package
      run: pip install python-semantic-release

    - name: Determine Version
      id: version
      run: |
        echo "::set-output name=version::$(semantic-release print-version)"
        echo ${{ github.actor }}

    - name: Update Version
      if: ${{ !contains(steps.gitversion.outputs.version,'No') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        semantic-release version
        echo "TAGGED"
