name: changelogs

on:
  push:
    branches:
      - '**'

jobs:
  update_changelogs:
    runs-on: ubuntu-20.04
    outputs:
      output1: ${{ steps.gitversion.outputs.version }}
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install package
      run: pip install python-semantic-release

    - name: Git setup
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "github-actions"

    - name: Determine Version
      id: gitversion
      run: |
        semantic-release print-version
        echo "::set-output name=version::$(semantic-release print-version)"

    - name: Update Version
      if: ${{ !contains(steps.gitversion.outputs.version,'No') }}
      run: |
        semantic-release version
        echo ${{ steps.gitversion.outputs.version }}

    - name: Install pandoc
      if: ${{ !contains(steps.gitversion.outputs.version,'No') }}
      run: brew install pandoc

    - name: Get Changelog
      if: ${{ !contains(steps.gitversion.outputs.version,'No') }}
      id: changelogs
      run: |
        semantic-release changelog >> temp.md
        pandoc temp.md -f markdown_strict -t rst -o temp.rst
        echo "" >> temp.rst
        cat temp.rst CHANGELOG.rst > tmp && mv tmp CHANGELOG.rst

    - name: create pull request
      if: ${{ !contains(steps.gitversion.outputs.version,'No') }}
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: 'docs: Bump the Version and update Changelogs'
        branch: update-changelogs
        title: Upgrade the version